### ISSUE TITLE
File -> Open leads to a Segmentation fault

### ISSUE THREAD

**Issue by philippeVerney** [F2I-Consulting/fespp#20]
Hi Cedric,

The new way to open an EPC Document is to click on the EPC blue icon.
However, it is still possible to to file->open and select an EPC document. And, when doing the latter, a seg fault occurs.
Can you either:

- disable this way to import EPC document (only keeping the blue icon)
- or repair the File->Import functionality

Thanks

**Comment by cedricRobert** [comment]
File->Import functionality: repaired with version 2.1
