### ISSUE TITLE
Minimum width of "selection widget"' is too large

### ISSUE THREAD

**Issue by philippeVerney** [F2I-Consulting/fespp#22]
Hi Cedric,

The width of the "selection widget" looks to have a minimal size. And this minimal size is really uncomfortable on some low resolutions screen.
Would it be possible to disable this minimal size please or to make it really less.
Remark : other panels from Paraview have a good behaviour which should be mimic ideally.

Thanks

**Comment by cedricRobert** [comment]
fix with version 2.1
