### ISSUE TITLE
Sporadic Grid2Representation loading on paraview

### ISSUE THREAD

**Issue by aleshaleksey** [F2I-Consulting/fespp#39]
Hello Fespp team,

I am writing on behalf of the GiGa infosystems team with something between a query and bug report.

Loading of Grid2dRepresentation by fespp seems to be sporadic. By this I mean that two Resqml files written by the same writer and differing, as far as we can tell only in uuids for various parts do not behave the same when opened by the FESPP plugin for paraview (one opens and views, the other only doesn't). We are fairly sure that the files are at least somewhat valid as they:
1. Come from the same geometry and are written by the exact same version of the exact same writer.
2. Have been checked by the geosiris validator for epc files (http://webstudio.geosiris.com/editor).
3. Have been checked by hdf5 tools (https://docs.hdfgroup.org/hdf5/develop/_view_tools_command.html).
4. An "in house" parser successfully and correctly parses the files (although that should not be taken as proof of validity, only that the files are not "messed up beyond all recognition").

We are quite sure that this is not some kind of paraview flakiness, since repeatedly opening the same files with paraview gives the same result. We also observe that the plugin does not open the Grid2dRepresentation from the GeoSiris example file in the Energistics Resqml v2.01 documentation pack.

Basic further information:
```
Version: 5.11.1
VTK Version: 9.2.6-1051-gfe3a658a4a
Qt Version: 5.12.8
```
FESPP version: 3.0.0 (master, commit 2b2d8e77242ceed169ff0ac58bfefef773c04989)
Runtime: Ubuntu 20.04.1

I can provide more details and the example misbehaving files and general background if required. At this point I am not sure whether this is a bona fide bug (either in the Writer, or in Fespp or paraview), or whether this is expected behaviour.

Thanks in advance for any insight on this issue.

**Comment by aleshaleksey** [comment]
Thank you  for you swift and concise reply.

This mismatch in version information may be the key to why our files do not behave correctly (or it might not). It looks like there is some sloppiness in the writing of versions in our files as well too (although in our case the version string is missing BOTH on the "resqml2:RepresentedInterpretation" of the obj_Grid2dRepresentation" file AND the "eml:Citation" of the .

I will have a look at our files and if it turns out that observing a stricter adherence to the standard does not solve it, I will send you the files.

**Comment by philippeVerney** [comment]
Having no "version attribute" at all in XMLs of EPC is the most recommended way since very few applications handle RESQML multiversionned dataobjects. Your files look to behave correctly from regarding this aspect except if you care about supporting versionned dataobjects

I'll test your files when you attach them and will come back to you with more information.

**Comment by aleshaleksey** [comment]
Hello @philippeVerney,

I have implemented your recommendation and removed the version information. This seems to have fixed the problem of the writer occasionally writing a file that paraview-FESPP can't open. As such I would like to thank you for the advise and help that you have given.

I will also attach 3 files, which may be interesting (or not, it depends on how rare and obscure this mode of failure is). "grid2d-failing" and "grid2d-working" are the files  from the writer where the problem was encountered: They are the same geometry written by the same writer, one displays, the other mysteriously fails. The other file, "grid2d-new" is the same geometry written by the writer with all version information removed. ~40 writes with the updated writer have not produced a single file that fails to display, so I am fairly satisfied that versions were likely the cause of the problem.

[gsurf-new.tar.gz](https://github.com/F2I-Consulting/fespp/files/13966061/gsurf-new.tar.gz)
[grid2d-failing.tar.gz](https://github.com/F2I-Consulting/fespp/files/13966062/grid2d-failing.tar.gz)
[grid2d-working.tar.gz](https://github.com/F2I-Consulting/fespp/files/13966063/grid2d-working.tar.gz)

**Comment by philippeVerney** [comment]
Hi @aleshaleksey 

Thanks for the attached files.
To me "failing" and "working" are not valid. They refer to a '0' versioned HdfProxy/obj_EpcExternalPartReference which is actually not versioned in the EPC. They also reference a '0' versioned HorizonFeature/obj_GeneticBoundaryFeature which does not exist neither.
As referencing inexistent versioned dataobject still leads in an undefined behavior (FESAPI functionality lack), I am not so much surprised that one fails and the other works. But, both should fail.

"new" file is fine (no usage of versioned dataobject) : I am not surprised and I'm happy that it works with FESPP.

Ideally, we would like FESPP to validate EPC files before import but this is not the main purpose of FESPP. We only focus on visualizing RESQML data mainly cause of limited resources. We cannot enlarge our scope and warn/raise all issues to the user about the EPC. We do some but this kind of detection would be too much time for us to dedicate and it cannot be a priority.
To me, this is the responsability of a validator such as the one from Geosiris. But again here, they have limite resources. I just ping @untereiner in case geosiris would be interested.

Finally, your "new" files look good except the eml:format attribute which does not honor the standard.
The [official RESQML2.0.1 documentation](https://docs.energistics.org/#ECOM2/ECOM2_TOPICS/ECOM2-000-008-0-R-sv2000.html) is 

> The ISO format for this is [vendor:applicationName]/fileExtension where the application name includes the version number of the application.

Nowadays, the latest recommendation (EML2.3 documentation) is

> organizationName:applicationName:applicationVersion/format

which would be in your case something like "GiGa infosystems:GST:3.13.0"

**Comment by untereiner** [comment]
Hi @philippeVerney  and @aleshaleksey 
Thanks for pointing out! Clean this old example would be nice I think.
@aleshaleksey If I remember correctly when exporting in an epc from the RESQML webstudio it cleans out the version information. It was because of this lack of support. 
I you have any issue do not hesitate to post it [here](https://github.com/geosiris-technologies/webstudio)

**Comment by aleshaleksey** [comment]
Hello @untereiner ,
Currently there are no other major questions.
For now I would like to just say that it is really nice to work with package maintainers who are so quick and on top of their package.
Thanks again, and if we have any more issues, we will be in touch.
