### ISSUE TITLE
Wrong component specification

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fespp#42]
In the CMakeLists.txt at line:
`find_package(ParaView 5.11.0 REQUIRED pqCore)`

I suppose that you wanted to write this: 
`find_package(ParaView 5.11.0 REQUIRED COMPONENTS pqCore)`

but I think specifying a component is useless since your don't use it in a `target_link_libraries`.
I whould write it as :
`find_package(ParaView 5.11.0 REQUIRED)`

PS: I have a compilation issue with this specific ligne in my spack recipe. The develop branch in my fork (with this change) works without any issues.

**Comment by philippeVerney** [comment]
Thanks @untereiner for this issue.

We are exactly now working on it (thanks to another company report).
Yes we plan to only have `find_package(ParaView 5.11.0 REQUIRED)` or even `find_package(ParaView 5.10.0 REQUIRED)`
Still some tests to do but you may have a fix quickly (on next thursday) in the dev branch if tests are successfull.

**Comment by cedricRobert** [comment]
pqcore and Qt in general are not used since the plugin v3.
A cleaning is done.
