### ISSUE TITLE
type mismatch

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fespp#43]
In the v3.3 branch there are lot of `int` that where replaced by `uint32_t` but in the vtk API we can find: 
```
int vtkDataAssembly::AddNode 	
    id of the newly added node on success, else -1. 
```
I think unsigned integers where needed

PS: what make me think was this error when loading an epc
```
had to make up a value for selection

(  98.121s) [paraview        ]vtkPartitionedDataSetCo:217    ERR| invalid partition index '1'
(  98.285s) [paraview        ]vtkPartitionedDataSetCo:217    ERR| invalid partition index '1'
(  99.650s) [paraview        ]vtkPartitionedDataSetCo:217    ERR| invalid partition index '1'
```

**Comment by philippeVerney** [comment]
Since v3.3 branch is today in sync with master branch which is in ysnc with 3.2.0 tag, it may be a current problem.
If you have more insights (epc file for example and/or steps to reproduce) on how to reproduce that, please share. We'll look at it anyhow

**Comment by untereiner** [comment]
I just realized the version naming. Yes it is not v3.3 it is in the commit that created v3.2.0

**Comment by cedricRobert** [comment]
Thanks for the feedback.
Indeed, the typing changes were not correct.

the error is not related to the typing.
A consistency problem in the dataset id results in a recovery of a non-existent dataset (out of range).
